# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache-dependency-path: server/go.sum

    - name: Install Protoc
      uses: arduino/setup-protoc@v2
    - name: Installing protoc-gen-go
      run: |
        go get google.golang.org/protobuf/cmd/protoc-gen-go
        go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
        go install google.golang.org/protobuf/cmd/protoc-gen-go
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
    - name: Generating protos
      run: |
        mkdir -p $GO_DST_DIR
        protoc -I=$SRC_DIR \
        --go_out=$GO_DST_DIR --go_opt=module=github.com/sangharsh/color-sort \
        --go-grpc_out=$GO_DST_DIR --go-grpc_opt=module=github.com/sangharsh/color-sort \
        $SRC_DIR/game.proto
      env:
        SRC_DIR: ../proto
        GO_DST_DIR: ./gen

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
